resolv-file=/etc/resolv.conf.orig
listen-address=127.0.0.1
bind-interfaces
mx-host=app.wild.ziti.test,mail.wild.ziti.test,10
mx-host=app.wild.ziti.test,mail2.wild.ziti.test,20
txt-record=app.wild.ziti.test,"v=spf1 -all"
srv-host=_sip._tcp.app.wild.ziti.test,sip.wild.ziti.test,5060,1,5
