//! The `ServiceBinding` handle: a live registration of this identity as a host of a service. Owns
//! the `EdgeChannel` (so its background rx-loop stays alive for the binding's lifetime), exposes
//! the accept surface (`accept`/`accept_pending`, which delegate to the `edge/data/` machinery)
//! and the teardown (`close` = Unbind then close). Oracle: sdk-golang
//! `ziti/edge/network/hosting_conn.go` (`edgeHostConn`).

use crate::channel::message::Message;
use crate::edge::data::{EdgeChannel, EdgeConn, PendingAccept};
use crate::edge::error::EdgeError;
use tokio::sync::mpsc;

/// A live service binding: this identity is registered as a host of the service. Owns the
/// `EdgeChannel` so its background rx-loop stays alive (the channel's `Drop` aborts the
/// rx-loop). Slice 7a registers only; accepting incoming dials is slice 7b. One binding per
/// channel.
pub struct ServiceBinding {
    // `pub(super)` (= `pub(in crate::edge::bind)`) so the sibling submodules that build this handle
    // by struct literal — `flow.rs` (`bind_inner`) and `tests_binding.rs` — keep compiling after the
    // F6 tramo 10 split. Syntax, not scope: in the monolith these were private to `edge::bind` and
    // visible to its descendants; `pub(super)` from here is exactly the same set. Nothing outside
    // `crate::edge::bind` gains access (spec §5.1a).
    pub(super) conn_id: u32,
    pub(super) token: String,
    pub(super) channel: EdgeChannel,
    /// The bind's accept queue receiver (inbound `Dial`/`StateClosed`), from `send_bind`.
    pub(super) bind_rx: mpsc::Receiver<Message>,
    /// The host's static X25519 keypair for an `encryptionRequired` service (advertised in the
    /// Bind, reused for every accepted child's key exchange); `None` for a plaintext service.
    pub(super) keypair: Option<crate::edge::crypto::KeyPair>,
}

// Manual Debug (prints conn_id) — NOT #[derive], which would require EdgeChannel: Debug and
// cascade Debug impls into the edge/data/mod.rs primitives (a scope violation caught in slice 6).
impl std::fmt::Debug for ServiceBinding {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("ServiceBinding")
            .field("conn_id", &self.conn_id)
            .finish_non_exhaustive()
    }
}

impl ServiceBinding {
    /// A `Weak` handle to the underlying channel state, for the live-channel registry (OIDC-2). The
    /// registry upgrades it to push a rotated token while this `ServiceBinding` lives (the case OIDC-2
    /// exists for: a long-lived idle binding), and prunes it once dropped. Registered by
    /// `bind_with_timeout` on success.
    #[must_use]
    pub(crate) fn channel_weak(&self) -> std::sync::Weak<crate::edge::data::ChannelState> {
        self.channel.state_weak()
    }

    /// The bind's channel, for the live-token-push live test (assert the router replies
    /// `UpdateTokenSuccess` directly). Test-only — production pushes via the registry.
    #[cfg(test)]
    #[must_use]
    pub(crate) fn channel_for_test(&self) -> &EdgeChannel {
        &self.channel
    }

    /// The bind connection id assigned for this terminator.
    #[must_use]
    pub fn conn_id(&self) -> u32 {
        self.conn_id
    }

    /// Accept the next inbound dial, returning a live `EdgeConn` for the child connection.
    /// Serves both plaintext children (`keypair: None`) and e2e-encrypted children
    /// (`keypair: Some`); the encryption mode is determined by what was advertised in the Bind.
    /// Rejected dials (bad token / crypto failure) are handled internally (`DialFailed` + keep
    /// accepting); a dial with no readable `RouterProvidedConnId` is NOT rejected — the child id is
    /// GENERATED (`hosting_conn.go:290-296`). Returns `ListenerClosed` when the router closes the
    /// bind or the channel dies. The binding owns the channel, so accepted conns stay alive
    /// while the binding lives.
    ///
    /// # Errors
    /// - `EdgeError::ListenerClosed` if the listener is closed (router `StateClosed` / channel death).
    /// - `EdgeError::Channel` if writing the accept reply fails.
    /// - `EdgeError::AcceptStartFailed` if the child's conn-id was GENERATED by us (the `Dial` carried
    ///   no readable `RouterProvidedConnId`) and the router's `StateConnected` never arrives within the
    ///   5s budget, or arrives with an unexpected content type.
    pub async fn accept(&mut self) -> Result<EdgeConn, EdgeError> {
        self.channel
            .accept_next(
                self.conn_id,
                &self.token,
                self.keypair.as_ref(),
                &mut self.bind_rx,
            )
            .await
    }

    /// Accept the next inbound dial but DO NOT acknowledge it yet, returning a [`PendingAccept`]
    /// (validated + registered + crypto-computed, no DialSuccess on the wire). A forwarding host
    /// (`tunnel::host`) dials its target and then calls [`PendingAccept::complete_success`] (reachable
    /// → DialSuccess + crypto header) or [`PendingAccept::complete_failed`] (unreachable → DialFailed)
    /// — the faithful accept-then-dial order, so an unreachable target makes the dialer's `connect()`
    /// fail instead of succeed-then-EOF. Rejected dials (bad token / crypto failure) are still handled
    /// internally (DialFailed + keep accepting); a missing or unreadable `RouterProvidedConnId` is
    /// NOT a rejection — the child id is GENERATED. The `PendingAccept` owns an
    /// `Arc<ChannelState>` clone, so this `&mut self` borrow ends on return — the accept loop can pull
    /// the next dial while a child's target dial is in flight.
    ///
    /// # Errors
    /// - `EdgeError::ListenerClosed` if the listener is closed (router `StateClosed` / channel death).
    pub async fn accept_pending(&mut self) -> Result<PendingAccept, EdgeError> {
        self.channel
            .accept_pending(
                self.conn_id,
                &self.token,
                self.keypair.as_ref(),
                &mut self.bind_rx,
            )
            .await
    }

    /// Unbind the terminator and close the channel. The Unbind is best-effort (teardown
    /// notification, fire-and-forget in the oracle; on a closing channel the write may
    /// legitimately fail) — its error is intentionally ignored. The channel close result IS
    /// propagated.
    ///
    /// # Errors
    /// Propagates the channel close error.
    pub async fn close(self) -> Result<(), EdgeError> {
        let ServiceBinding {
            conn_id,
            token,
            channel,
            bind_rx: _,
            keypair: _,
        } = self;
        let _ = channel.send_unbind(conn_id, &token).await;
        channel.close().await
    }
}
